### ISSUE TITLE
More than 1 vault causes password missmatch

### ISSUE THREAD

**Issue by korjik** [peacetara/slab#11]
Steps to reproduce:
1. Clean 1Password installation. Add vault. Add password to the vault to the keychain. Use slab, all works fine.
2. Add second vault.
3. Slab outputs:

> The password supplied does not unlock 1Password

I myself have 2 vaults - 1 for work, another for family that I share/sync with my family. slab doesn't work in this ecosystem with more than 1 vault.

**Comment by korjik** [comment]
Here's my profiles:
```
$ sqlite3 '/Users/akozhokaru/Library/Application Support/1Password 4/Data/OnePassword.sqlite'
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> select id, profile_name from profiles;
2|Family
1|default
```
And here's some interactive python run:
```
k.unlock(password, profileName='default')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/slab-0.1.1-py3.7.egg/onepassword/crypt_util.py", line 170, in opdata1_decrypt_item
  File "/usr/local/lib/python3.7/site-packages/cryptography-2.6.1-py3.7-macosx-10.14-x86_64.egg/cryptography/hazmat/primitives/hmac.py", line 67, in verify
    ctx.verify(signature)
  File "/usr/local/lib/python3.7/site-packages/cryptography-2.6.1-py3.7-macosx-10.14-x86_64.egg/cryptography/hazmat/backends/openssl/hmac.py", line 75, in verify
    raise InvalidSignature("Signature did not match digest.")
cryptography.exceptions.InvalidSignature: Signature did not match digest.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/slab-0.1.1-py3.7.egg/slab/slablib.py", line 104, in unlock
  File "/usr/local/lib/python3.7/site-packages/slab-0.1.1-py3.7.egg/slab/slablib.py", line 80, in _loadItems
  File "/usr/local/lib/python3.7/site-packages/slab-0.1.1-py3.7.egg/slab/slablib.py", line 110, in decrypt_overview
  File "/usr/local/lib/python3.7/site-packages/slab-0.1.1-py3.7.egg/onepassword/crypt_util.py", line 172, in opdata1_decrypt_item
ValueError: HMAC did not match for opdata1 record
```

The issue is that when there's a single vault running, it works fine and once I add another vault, it gets borked.

**Comment by peacetara** [comment]
I don't have 1password6 installed anywhere anymore, so it's not something I'm able to work on.  I'd happily accept a patch.

I think what's going on is this select statement:
https://github.com/peacetara/slab/blob/0d59055122585ae8b45f5847d337c5175b59542b/src/python/slab/slablib.py#L75

needs to have the profile added to the where clause, so it will only return items for the unlocked profile, which can be gotten from self.profile['id']  similar to whats done in the _categories() call here:
https://github.com/peacetara/slab/blob/0d59055122585ae8b45f5847d337c5175b59542b/src/python/slab/slablib.py#L43

I assume the items table also has a profile_id column, but I don't know that for sure.

that *should* fix the issue.

Again, I don't have 1password6 anymore, nor multiple vaults, so not something I can test. 

so someone adventurous(maybe you?) would need to see about a profile_id column on the items table, and then update the SQL query and see if that fixes it.  I think it will, if it does, please send a patch!

Also, you will probably need to expose the profileName option to the UI somehow, so you can select which profile to query from.. that's done in the unlock() call:
https://github.com/peacetara/slab/blob/0d59055122585ae8b45f5847d337c5175b59542b/src/python/slab/main.py#L153

I'd recommend getting it from a command line option: -p <profilename> or something, and then passing it into the k.unlock() call.

**Comment by korjik** [comment]
Let me follow the lead and try to fix it! Thanks!

**Comment by peacetara** [comment]
good luck!
